# Generated by Django 5.2.4 on 2025-07-10 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_customuser_address_customuser_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Internship', 'Internship'), ('Contract', 'Contract')], default='Full-time', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_range',
            field=models.CharField(default='Not specified', max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
